# Generated by Django 5.1.6 on 2025-02-14 04:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('user_type', models.CharField(choices=[('STUDENT', 'Student'), ('EMPLOYEE', 'Employee')], max_length=150)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('is_lock', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('contact_no', models.CharField(max_length=15, unique=True)),
                ('aadhar_no', models.CharField(max_length=12, unique=True)),
                ('pan_no', models.CharField(max_length=10, unique=True)),
                ('biometric_id', models.CharField(max_length=20, unique=True)),
                ('blood_group', models.CharField(max_length=3)),
                ('date_of_birth', models.DateField()),
                ('date_of_joining', models.DateField()),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('pincode', models.CharField(max_length=6)),
                ('is_archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('designation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.designation')),
                ('employee_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.role')),
                ('institute_department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.department')),
                ('salutation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.salutation')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=15)),
                ('blood_group', models.CharField(max_length=3)),
                ('date_of_birth', models.DateField()),
                ('aadhar_number', models.CharField(max_length=12, unique=True)),
                ('tenth_score_type', models.CharField(choices=[('CGPA', 'CGPA'), ('Percentage', 'Percentage')], max_length=10)),
                ('tenth_score', models.FloatField()),
                ('twelfth_score_type', models.CharField(choices=[('CGPA', 'CGPA'), ('Percentage', 'Percentage')], max_length=10)),
                ('twelfth_score', models.FloatField()),
                ('graduation_background', models.CharField(max_length=100)),
                ('graduation_score_type', models.CharField(choices=[('CGPA', 'CGPA'), ('Percentage', 'Percentage')], max_length=10)),
                ('graduation_score', models.FloatField()),
                ('date_of_joining', models.DateField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('caste', models.CharField(max_length=50)),
                ('score_card', models.TextField()),
                ('experience_status', models.CharField(choices=[('Experienced', 'Experienced'), ('Non-Experienced', 'Non-Experienced')], max_length=20)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=10)),
                ('father_name', models.CharField(max_length=100)),
                ('father_contact_number', models.CharField(max_length=15)),
                ('father_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('father_aadhar_number', models.CharField(max_length=12, unique=True)),
                ('mother_name', models.CharField(max_length=100)),
                ('mother_contact_number', models.CharField(max_length=15)),
                ('mother_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('mother_aadhar_number', models.CharField(max_length=12, unique=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('experience_details', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_batch', to='administration.batch')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_course', to='administration.course')),
                ('student_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.role')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
