# Generated by Django 5.1.6 on 2025-02-28 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_studentdocument_userotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='achievements',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='employee',
            name='additional_details',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='employee',
            name='articles',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='employee',
            name='conferences',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='employee',
            name='education',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='employee',
            name='employee_type',
            field=models.CharField(choices=[('Teaching', 'Teaching'), ('Non-Teaching', 'Non-Teaching')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='experience',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='employee',
            name='interest',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='employee',
            name='publications',
            field=models.JSONField(default=list),
        ),
    ]
