# Generated by Django 5.1.6 on 2025-02-28 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_employee_achievements_employee_additional_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='aicte_permanent_id',
            field=models.CharField(default=1, max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='taxila_roll_number',
            field=models.CharField(default=1, max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
