# Generated by Django 5.1.6 on 2025-02-28 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_student_aicte_permanent_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='appointment_type',
            field=models.CharField(choices=[('Reguler', 'Reguler'), ('Guest', 'Guest')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='father_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='industry_exprience',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='mother_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='research_exprience',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='teaching_exprience',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='district',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='dropped',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='passout_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='pwd',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='religion',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
