# Generated by Django 5.1.6 on 2025-02-28 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_employee_appointment_type_employee_father_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentFeeStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_fee', models.BooleanField(default=False)),
                ('program_fee_installment1_paid', models.BooleanField(default=False)),
                ('program_fee_installment2_paid', models.BooleanField(default=False)),
                ('enrollment_fee_paid', models.BooleanField(default=False)),
                ('caution_fee_tuition', models.BooleanField(default=False)),
                ('extra_penalty', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_fee', to='users.student')),
            ],
        ),
    ]
