# Generated by Django 5.1.6 on 2025-03-01 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_studentfeestatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='appointment_type',
            field=models.CharField(max_length=50),
        ),
    ]
