# Generated by Django 5.1.6 on 2025-03-01 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_employee_appointment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='appointment_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
