# Generated by Django 5.1.6 on 2025-03-01 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_employee_appointment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employee_type',
            field=models.CharField(blank=True, choices=[('Teaching', 'Teaching'), ('Non-Teaching', 'Non-Teaching')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='father_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='industry_exprience',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='employee',
            name='mother_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='research_exprience',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='employee',
            name='teaching_exprience',
            field=models.FloatField(default=0),
        ),
    ]
