# Generated by Django 5.1.6 on 2025-03-01 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_employee_employee_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='industry_exprience',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='research_exprience',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='teaching_exprience',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
