# Generated by Django 5.1.6 on 2025-03-01 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_employee_industry_exprience_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='aicte_permanent_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='district',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='religion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='taxila_roll_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
