# Generated by Django 5.1.6 on 2025-03-01 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_student_aicte_permanent_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='dropped',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='passout_status',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='pwd',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
