# Generated by Django 5.1.6 on 2025-03-01 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_student_dropped_alter_student_passout_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='dropped',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='passout_status',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='pwd',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
