# Generated by Django 5.1.6 on 2025-03-01 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_student_dropped_alter_student_passout_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacultyMentorship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculty_membership', to='users.employee')),
                ('students', models.ManyToManyField(related_name='faculty_membership', to='users.student')),
            ],
        ),
    ]
