# Generated by Django 5.1.6 on 2025-03-01 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_facultymentorship'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='caste',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='taxila_roll_number',
            new_name='enrollment_number',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='score_card',
            new_name='entrance_score_card',
        ),
        migrations.AddField(
            model_name='student',
            name='entrance_appear',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='entrance_appear_year',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='experience_status',
            field=models.BooleanField(),
        ),
    ]
