# Generated by Django 5.1.6 on 2025-03-10 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_alter_employee_aadhar_no_alter_employee_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facultymentorship',
            old_name='faculty',
            new_name='user',
        ),
    ]
