# Generated by Django 5.1.6 on 2025-03-31 09:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0024_alter_attendance_class_schedule_and_more'),
        ('users', '0020_rename_faculty_facultymentorship_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='designation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='administration.designation'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='administration.role'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='institute_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='administration.department'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='salutation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='administration.salutation'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='employee', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='facultymentorship',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='faculty_membership', to='users.employee'),
        ),
        migrations.AlterField(
            model_name='student',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_batch', to='administration.batch'),
        ),
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_course', to='administration.course'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='administration.role'),
        ),
        migrations.AlterField(
            model_name='student',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='studentdocument',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Student_document', to='users.student'),
        ),
        migrations.AlterField(
            model_name='studentfeestatus',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_fee', to='users.student'),
        ),
        migrations.AlterField(
            model_name='userotp',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_otp', to=settings.AUTH_USER_MODEL),
        ),
    ]
