# Generated by Django 5.1.6 on 2025-04-23 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_remove_employee_employee_role_employee_employee_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentfeestatus',
            old_name='program_fee_installment1_paid',
            new_name='program_fee_paid',
        ),
        migrations.RemoveField(
            model_name='studentfeestatus',
            name='program_fee_installment2_paid',
        ),
    ]
