# Generated by Django 5.1.6 on 2025-02-14 05:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_classes', models.IntegerField()),
                ('classes_completed', models.IntegerField(default=0)),
                ('weightage_external', models.FloatField()),
                ('weightage_internal', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_mappings', to='administration.batch')),
                ('course', models.ManyToManyField(related_name='subject_mappings', to='administration.course')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_mappings', to='users.employee')),
                ('specialization', models.ManyToManyField(related_name='subject_mappings', to='administration.specialization')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_mappings', to='administration.subject')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_mappings', to='administration.terms')),
            ],
            options={
                'unique_together': {('batch', 'subject', 'term', 'faculty')},
            },
        ),
    ]
