# Generated by Django 5.1.6 on 2025-02-14 05:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_subjectmapping'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_mappings', to='administration.batch')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_mappings', to='administration.course')),
                ('specialization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_mappings', to='administration.specialization')),
                ('student', models.ManyToManyField(related_name='student_mappings', to='users.student')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_mappings', to='administration.terms')),
            ],
        ),
    ]
