# Generated by Django 5.1.6 on 2025-02-14 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0004_classschedule_attendance'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('INTERNAL', 'Internal'), ('EXTERNAL', 'External')], max_length=150)),
                ('name', models.CharField(max_length=250)),
                ('max_marks', models.FloatField(default=0)),
                ('has_subcomponents', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject_mapping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='administration.subjectmapping')),
            ],
        ),
        migrations.CreateModel(
            name='ComponentMarks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obtained_marks', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='component_marks', to='administration.component')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='component_marks', to='users.student')),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('type', models.CharField(choices=[('mid-term', 'mid-term'), ('final-term', 'final-term')], max_length=250)),
                ('is_cancel', models.BooleanField(default=False)),
                ('is_reschedule', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_subject', to='administration.component')),
            ],
        ),
        migrations.CreateModel(
            name='SubComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('max_marks', models.FloatField()),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcomponents', to='administration.component')),
            ],
        ),
        migrations.CreateModel(
            name='SubComponentMarks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obtained_marks', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcomponent_marks', to='users.student')),
                ('subcomponent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcomponent_marks', to='administration.subcomponent')),
            ],
        ),
    ]
