# Generated by Django 5.1.6 on 2025-02-17 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0005_component_componentmarks_exam_subcomponent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='credit',
            field=models.FloatField(),
        ),
    ]
