# Generated by Django 5.1.6 on 2025-02-18 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0006_alter_subject_credit'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectmapping',
            name='type',
            field=models.CharField(choices=[('main', 'main'), ('reset-1', 'reset-1'), ('reset-2', 'reset-2')], default=1, max_length=150),
            preserve_default=False,
        ),
    ]
