# Generated by Django 5.1.6 on 2025-02-18 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0007_subjectmapping_type'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='type',
        ),
        migrations.CreateModel(
            name='ResetExamRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved')], default='Pending', max_length=20)),
                ('type', models.CharField(choices=[('reset-1', 'reset-1'), ('reset-2', 'reset-2')], max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resets', to='administration.batch')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resets', to='administration.course')),
                ('specialization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resets', to='administration.specialization')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resets', to='users.student')),
                ('subjects', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resets', to='administration.subjectmapping')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resets', to='administration.terms')),
            ],
        ),
    ]
