# Generated by Django 5.1.6 on 2025-02-18 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0008_remove_exam_type_resetexamrequest'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subjectmapping',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='resetexamrequest',
            name='type',
            field=models.CharField(choices=[('resit-1', 'resit-1'), ('resit-2', 'resit-2')], max_length=150),
        ),
        migrations.AlterField(
            model_name='subjectmapping',
            name='type',
            field=models.CharField(choices=[('main', 'main'), ('resit-1', 'resit-1'), ('resit-2', 'resit-2')], max_length=150),
        ),
        migrations.AlterUniqueTogether(
            name='subjectmapping',
            unique_together={('batch', 'subject', 'term', 'faculty', 'type')},
        ),
    ]
