# Generated by Django 5.1.6 on 2025-02-25 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0010_batch_is_active_course_duration_in_months_and_more'),
        ('users', '0002_studentdocument_userotp'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComponentAnswers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers_file', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='component_answer', to='administration.component')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='component_answer', to='users.student')),
            ],
        ),
    ]
