# Generated by Django 5.1.6 on 2025-03-01 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0012_alter_course_name_alter_department_name_and_more'),
        ('users', '0015_rename_caste_student_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternshipCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('mentor_name', models.CharField(max_length=200)),
                ('mentor_mobile_number', models.CharField(max_length=13)),
                ('location', models.TextField()),
                ('offer_letter', models.FileField(upload_to='internship_offer_letter')),
                ('campus_joining_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intership', to='users.student')),
                ('subject_mapping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intership', to='administration.subjectmapping')),
            ],
        ),
        migrations.CreateModel(
            name='InternshipReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_report', models.FileField(blank=True, null=True, upload_to='internship_reports/')),
                ('weekly_report', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('internship_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intern_company', to='administration.internshipcompany')),
            ],
        ),
    ]
