# Generated by Django 5.1.6 on 2025-03-04 05:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0013_internshipcompany_internshipreport'),
        ('users', '0017_auditlog_ip_address_auditlog_request_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internshipreport',
            name='internship_company',
        ),
        migrations.AddField(
            model_name='internshipreport',
            name='component',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='intern_report', to='administration.component'),
        ),
        migrations.AddField(
            model_name='internshipreport',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='intern_report', to='users.student'),
        ),
    ]
