# Generated by Django 5.1.6 on 2025-03-05 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0014_remove_internshipreport_internship_company_and_more'),
        ('users', '0017_auditlog_ip_address_auditlog_request_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoticeBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1999)),
                ('date', models.DateField()),
                ('description', models.TextField()),
                ('valid_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notice_board', to='users.employee')),
            ],
        ),
    ]
