# Generated by Django 5.1.6 on 2025-03-10 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0017_alter_studentleaverequest_status_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentmapping',
            name='batch',
        ),
        migrations.RemoveField(
            model_name='studentmapping',
            name='course',
        ),
    ]
