# Generated by Django 5.1.6 on 2025-03-11 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0018_remove_studentmapping_batch_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='noticeboard',
            old_name='faculty',
            new_name='user',
        ),
    ]
