# Generated by Django 5.1.6 on 2025-03-13 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0019_rename_faculty_noticeboard_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticeboard',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='notice_board/'),
        ),
        migrations.AddField(
            model_name='studentmapping',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_mappings', to='administration.batch'),
        ),
        migrations.AddField(
            model_name='studentmapping',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_mappings', to='administration.course'),
        ),
    ]
