# Generated by Django 5.1.6 on 2025-03-19 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0020_noticeboard_file_studentmapping_batch_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectMappingSyllabus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mapping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_syllabus', to='administration.subjectmapping')),
            ],
        ),
    ]
