# Generated by Django 5.1.6 on 2025-03-19 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0021_subjectmappingsyllabus'),
        ('users', '0020_rename_faculty_facultymentorship_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='component',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subcomponent',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subcomponent',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='SubComponentAnswers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers_file', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcomponent_answer', to='users.student')),
                ('sub_component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcomponent_answer', to='administration.subcomponent')),
            ],
        ),
    ]
