# Generated by Django 5.1.6 on 2025-03-25 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0022_component_end_date_component_start_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='terms',
            name='is_current',
            field=models.BooleanField(default=False),
        ),
    ]
