# Generated by Django 5.1.6 on 2025-03-31 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0023_terms_is_current'),
        ('users', '0020_rename_faculty_facultymentorship_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='class_schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendances', to='administration.classschedule'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendances', to='users.student'),
        ),
        migrations.AlterField(
            model_name='classschedule',
            name='mapping',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schedules', to='administration.subjectmapping'),
        ),
        migrations.AlterField(
            model_name='component',
            name='subject_mapping',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='components', to='administration.subjectmapping'),
        ),
        migrations.AlterField(
            model_name='componentanswers',
            name='component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='component_answer', to='administration.component'),
        ),
        migrations.AlterField(
            model_name='componentanswers',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='component_answer', to='users.student'),
        ),
        migrations.AlterField(
            model_name='componentmarks',
            name='component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='component_marks', to='administration.component'),
        ),
        migrations.AlterField(
            model_name='componentmarks',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='component_marks', to='users.student'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exam_subject', to='administration.component'),
        ),
        migrations.AlterField(
            model_name='internshipcompany',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='intership', to='users.student'),
        ),
        migrations.AlterField(
            model_name='internshipcompany',
            name='subject_mapping',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='intership', to='administration.subjectmapping'),
        ),
        migrations.AlterField(
            model_name='internshipreport',
            name='component',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='intern_report', to='administration.component'),
        ),
        migrations.AlterField(
            model_name='internshipreport',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='intern_report', to='users.student'),
        ),
        migrations.AlterField(
            model_name='noticeboard',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notice_board', to='users.employee'),
        ),
        migrations.AlterField(
            model_name='resetexamrequest',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resets', to='administration.batch'),
        ),
        migrations.AlterField(
            model_name='resetexamrequest',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resets', to='administration.course'),
        ),
        migrations.AlterField(
            model_name='resetexamrequest',
            name='specialization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resets', to='administration.specialization'),
        ),
        migrations.AlterField(
            model_name='resetexamrequest',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resets', to='users.student'),
        ),
        migrations.AlterField(
            model_name='resetexamrequest',
            name='subjects',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resets', to='administration.subjectmapping'),
        ),
        migrations.AlterField(
            model_name='resetexamrequest',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resets', to='administration.terms'),
        ),
        migrations.AlterField(
            model_name='studentleaverequest',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.student'),
        ),
        migrations.AlterField(
            model_name='studentmapping',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='student_mappings', to='administration.batch'),
        ),
        migrations.AlterField(
            model_name='studentmapping',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='student_mappings', to='administration.course'),
        ),
        migrations.AlterField(
            model_name='studentmapping',
            name='specialization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_mappings', to='administration.specialization'),
        ),
        migrations.AlterField(
            model_name='studentmapping',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_mappings', to='administration.terms'),
        ),
        migrations.AlterField(
            model_name='subcomponent',
            name='component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subcomponents', to='administration.component'),
        ),
        migrations.AlterField(
            model_name='subcomponentanswers',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subcomponent_answer', to='users.student'),
        ),
        migrations.AlterField(
            model_name='subcomponentanswers',
            name='sub_component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subcomponent_answer', to='administration.subcomponent'),
        ),
        migrations.AlterField(
            model_name='subcomponentmarks',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subcomponent_marks', to='users.student'),
        ),
        migrations.AlterField(
            model_name='subcomponentmarks',
            name='subcomponent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subcomponent_marks', to='administration.subcomponent'),
        ),
        migrations.AlterField(
            model_name='subjectmapping',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subject_mappings', to='administration.batch'),
        ),
        migrations.AlterField(
            model_name='subjectmapping',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subject_mappings', to='users.employee'),
        ),
        migrations.AlterField(
            model_name='subjectmapping',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subject_mappings', to='administration.subject'),
        ),
        migrations.AlterField(
            model_name='subjectmapping',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subject_mappings', to='administration.terms'),
        ),
        migrations.AlterField(
            model_name='subjectmappingsyllabus',
            name='mapping',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subject_syllabus', to='administration.subjectmapping'),
        ),
    ]
