# Generated by Django 5.1.6 on 2025-04-03 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0024_alter_attendance_class_schedule_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=450)),
                ('date', models.DateTimeField()),
                ('venue', models.CharField(max_length=999)),
                ('type', models.CharField(max_length=999)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
