# Generated by Django 5.1.6 on 2025-04-08 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0025_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='is_submission',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subcomponent',
            name='is_submission',
            field=models.BooleanField(default=False),
        ),
    ]
