# Generated by Django 5.1.6 on 2025-04-07 07:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0025_events'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
