# Generated by Django 5.1.6 on 2025-04-08 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0026_component_is_submission_subcomponent_is_submission'),
        ('administration', '0027_alter_events_date'),
    ]

    operations = [
    ]
