# Generated by Django 5.1.6 on 2025-04-08 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0028_merge_20250408_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='subcomponent',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
