# Generated by Django 5.1.6 on 2025-04-10 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0029_component_is_active_subcomponent_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='ce_marks',
            field=models.FloatField(default=0),
        ),
    ]
