# Generated by Django 5.1.6 on 2025-04-18 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0030_attendance_ce_marks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='end_time',
        ),
        migrations.AddField(
            model_name='exam',
            name='duration',
            field=models.FloatField(default=3),
        ),
    ]
