# Generated by Django 5.1.6 on 2025-04-18 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0031_remove_exam_end_time_exam_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='HallTicketAnnounce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='holl_ticket', to='administration.batch')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='holl_ticket', to='administration.terms')),
            ],
        ),
    ]
