# Generated by Django 5.1.6 on 2025-04-21 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0032_hallticketannounce'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectmapping',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
