# Generated by Django 5.1.6 on 2025-04-22 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0033_subjectmapping_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamResultAnnounce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('main', 'main'), ('resit-1', 'resit-1'), ('resit-2', 'resit-2')], max_length=150)),
                ('is_active', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exam_result', to='administration.batch')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exam_result', to='administration.terms')),
            ],
        ),
    ]
