# Generated by Django 5.1.6 on 2025-04-22 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0034_examresultannounce'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resetexamrequest',
            name='specialization',
        ),
    ]
