# Generated by Django 5.1.6 on 2025-04-23 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0036_hallticketannounce_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectMappingNotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mapping', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subject_notes', to='administration.subjectmapping')),
            ],
        ),
    ]
