# Generated by Django 5.1.6 on 2025-04-23 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0037_subjectmappingnotes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resetexamrequest',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
