# Generated by Django 5.1.6 on 2025-04-29 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0038_alter_resetexamrequest_status'),
        ('users', '0023_rename_program_fee_installment1_paid_studentfeestatus_program_fee_paid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_type', models.CharField(choices=[('main', 'main'), ('resit-1', 'resit-1'), ('resit-2', 'resit-2')], max_length=150)),
                ('gpa', models.FloatField()),
                ('total_credit', models.FloatField()),
                ('total_credit_xgp', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='users.student')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='administration.terms')),
            ],
            options={
                'unique_together': {('student', 'term', 'result_type')},
            },
        ),
        migrations.CreateModel(
            name='FinalSubjectResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_marks', models.FloatField()),
                ('internal_marks', models.FloatField()),
                ('total_marks', models.FloatField()),
                ('is_pass', models.BooleanField()),
                ('grade', models.CharField(max_length=2)),
                ('grade_point', models.FloatField()),
                ('get_credit_xgp', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('final_result', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='final_result', to='administration.finalresult')),
                ('subject_mapping', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='final_result', to='administration.subjectmapping')),
            ],
        ),
    ]
