# Generated by Django 5.1.6 on 2025-04-30 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0039_finalresult_finalsubjectresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='resetexamrequest',
            name='criteria_first',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resetexamrequest',
            name='criteria_second',
            field=models.BooleanField(default=False),
        ),
    ]
