# Generated by Django 5.1.6 on 2025-05-13 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0040_resetexamrequest_criteria_first_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentmapping',
            unique_together={('batch', 'course', 'term', 'specialization')},
        ),
        migrations.AddConstraint(
            model_name='exam',
            constraint=models.UniqueConstraint(fields=('component',), name='unique_exam_component'),
        ),
    ]
