# Generated by Django 5.1.6 on 2025-06-07 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0041_alter_studentmapping_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examresultannounce',
            name='exam_period',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='examresultannounce',
            name='term_period',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
