# Generated by Django 5.1.6 on 2025-03-10 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('privacy', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rolepermission',
            name='permission',
        ),
        migrations.CreateModel(
            name='CustomPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=250, unique=True)),
                ('permission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='custom_permission', to='auth.permission')),
            ],
        ),
        migrations.AddField(
            model_name='rolepermission',
            name='custom_permission',
            field=models.ManyToManyField(related_name='role_permissions', to='privacy.custompermission'),
        ),
    ]
