# Generated by Django 5.1.6 on 2025-03-28 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('privacy', '0002_remove_rolepermission_permission_custompermission_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rolepermission',
            name='custom_permission',
        ),
        migrations.AddField(
            model_name='rolepermission',
            name='permission',
            field=models.ManyToManyField(related_name='role_permissions', to='auth.permission'),
        ),
        migrations.DeleteModel(
            name='CustomPermission',
        ),
    ]
