# Generated by Django 5.1.6 on 2025-03-31 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0024_alter_attendance_class_schedule_and_more'),
        ('privacy', '0003_remove_rolepermission_custom_permission_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolepermission',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='role_permissions', to='administration.role'),
        ),
    ]
